// Code generated by MockGen. DO NOT EDIT.
// Source: timeex\i-now-unix-nano.go

// Package timeex is a generated GoMock package.
package timeex

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockINowUnixNano is a mock of INowUnixNano interface
type MockINowUnixNano struct {
	ctrl     *gomock.Controller
	recorder *MockINowUnixNanoMockRecorder
}

// MockINowUnixNanoMockRecorder is the mock recorder for MockINowUnixNano
type MockINowUnixNanoMockRecorder struct {
	mock *MockINowUnixNano
}

// NewMockINowUnixNano creates a new mock instance
func NewMockINowUnixNano(ctrl *gomock.Controller) *MockINowUnixNano {
	mock := &MockINowUnixNano{ctrl: ctrl}
	mock.recorder = &MockINowUnixNanoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockINowUnixNano) EXPECT() *MockINowUnixNanoMockRecorder {
	return m.recorder
}

// UnixNano mocks base method
func (m *MockINowUnixNano) UnixNano() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnixNano")
	ret0, _ := ret[0].(int64)
	return ret0
}

// UnixNano indicates an expected call of UnixNano
func (mr *MockINowUnixNanoMockRecorder) UnixNano() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnixNano", reflect.TypeOf((*MockINowUnixNano)(nil).UnixNano))
}
