// Code generated by MockGen. DO NOT EDIT.
// Source: timeex\i-now-unix.go

// Package timeex is a generated GoMock package.
package timeex

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockINowUnix is a mock of INowUnix interface
type MockINowUnix struct {
	ctrl     *gomock.Controller
	recorder *MockINowUnixMockRecorder
}

// MockINowUnixMockRecorder is the mock recorder for MockINowUnix
type MockINowUnixMockRecorder struct {
	mock *MockINowUnix
}

// NewMockINowUnix creates a new mock instance
func NewMockINowUnix(ctrl *gomock.Controller) *MockINowUnix {
	mock := &MockINowUnix{ctrl: ctrl}
	mock.recorder = &MockINowUnixMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockINowUnix) EXPECT() *MockINowUnixMockRecorder {
	return m.recorder
}

// Unix mocks base method
func (m *MockINowUnix) Unix() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unix")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Unix indicates an expected call of Unix
func (mr *MockINowUnixMockRecorder) Unix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unix", reflect.TypeOf((*MockINowUnix)(nil).Unix))
}
