// Code generated by MockGen. DO NOT EDIT.
// Source: contract\i-model-deleted-on-setter.go

// Package contract is a generated GoMock package.
package contract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIModelDeletedOnSetter is a mock of IModelDeletedOnSetter interface.
type MockIModelDeletedOnSetter struct {
	ctrl     *gomock.Controller
	recorder *MockIModelDeletedOnSetterMockRecorder
}

// MockIModelDeletedOnSetterMockRecorder is the mock recorder for MockIModelDeletedOnSetter.
type MockIModelDeletedOnSetterMockRecorder struct {
	mock *MockIModelDeletedOnSetter
}

// NewMockIModelDeletedOnSetter creates a new mock instance.
func NewMockIModelDeletedOnSetter(ctrl *gomock.Controller) *MockIModelDeletedOnSetter {
	mock := &MockIModelDeletedOnSetter{ctrl: ctrl}
	mock.recorder = &MockIModelDeletedOnSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIModelDeletedOnSetter) EXPECT() *MockIModelDeletedOnSetterMockRecorder {
	return m.recorder
}

// SetDeletedOn mocks base method.
func (m *MockIModelDeletedOnSetter) SetDeletedOn(v int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeletedOn", v)
}

// SetDeletedOn indicates an expected call of SetDeletedOn.
func (mr *MockIModelDeletedOnSetterMockRecorder) SetDeletedOn(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeletedOn", reflect.TypeOf((*MockIModelDeletedOnSetter)(nil).SetDeletedOn), v)
}
