// Code generated by MockGen. DO NOT EDIT.
// Source: osex\i-env.go

// Package osex is a generated GoMock package.
package osex

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIEnv is a mock of IEnv interface
type MockIEnv struct {
	ctrl     *gomock.Controller
	recorder *MockIEnvMockRecorder
}

// MockIEnvMockRecorder is the mock recorder for MockIEnv
type MockIEnvMockRecorder struct {
	mock *MockIEnv
}

// NewMockIEnv creates a new mock instance
func NewMockIEnv(ctrl *gomock.Controller) *MockIEnv {
	mock := &MockIEnv{ctrl: ctrl}
	mock.recorder = &MockIEnvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIEnv) EXPECT() *MockIEnvMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockIEnv) Get(arg0 string, arg1 interface{}) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Get", arg0, arg1)
}

// Get indicates an expected call of Get
func (mr *MockIEnvMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIEnv)(nil).Get), arg0, arg1)
}
