// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahl5esoft/lite-go/api/session (interfaces: ICaller)

// Package session is a generated GoMock package.
package session

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	time "time"
)

// MockICaller is a mock of ICaller interface
type MockICaller struct {
	ctrl     *gomock.Controller
	recorder *MockICallerMockRecorder
}

// MockICallerMockRecorder is the mock recorder for MockICaller
type MockICallerMockRecorder struct {
	mock *MockICaller
}

// NewMockICaller creates a new mock instance
func NewMockICaller(ctrl *gomock.Controller) *MockICaller {
	mock := &MockICaller{ctrl: ctrl}
	mock.recorder = &MockICallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockICaller) EXPECT() *MockICallerMockRecorder {
	return m.recorder
}

// Get mocks base method
func (m *MockICaller) Get(arg0 string, arg1 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get
func (mr *MockICallerMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockICaller)(nil).Get), arg0, arg1)
}

// Set mocks base method
func (m *MockICaller) Set(arg0 interface{}, arg1, arg2 time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set
func (mr *MockICallerMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockICaller)(nil).Set), arg0, arg1, arg2)
}
